export const DEFAULT_PROVIDERS = [
  {
    id: 'openai',
    label: 'OpenAI',
    deployment: 'cloud',
    apiStyle: 'openai-compatible',
    apiKeyEnv: 'OPENAI_API_KEY',
    baseUrlEnv: 'OPENAI_BASE_URL',
    defaultBaseUrl: 'https://api.openai.com/v1',
    modelEnv: 'OPENAI_MODEL',
    defaultModel: 'gpt-4o-mini',
    capabilities: ['chat', 'reasoning', 'vision', 'speech-to-text', 'text-to-speech', 'embeddings', 'image-generation', 'tool-use'],
    scores: { quality: 9, speed: 8, cost: 5, privacy: 4 },
  },
  {
    id: 'anthropic',
    label: 'Anthropic',
    deployment: 'cloud',
    apiStyle: 'anthropic',
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    modelEnv: 'ANTHROPIC_MODEL',
    defaultModel: 'claude-3-5-sonnet-latest',
    capabilities: ['chat', 'reasoning', 'vision', 'tool-use'],
    scores: { quality: 9, speed: 7, cost: 4, privacy: 4 },
  },
  {
    id: 'google',
    label: 'Google',
    deployment: 'cloud',
    apiStyle: 'google',
    apiKeyEnv: 'GOOGLE_API_KEY',
    modelEnv: 'GOOGLE_MODEL',
    defaultModel: 'gemini-1.5-pro',
    capabilities: ['chat', 'reasoning', 'vision', 'speech-to-text', 'text-to-speech', 'embeddings', 'image-generation', 'video-generation', 'tool-use'],
    scores: { quality: 8, speed: 8, cost: 6, privacy: 4 },
  },
  {
    id: 'openrouter',
    label: 'OpenRouter',
    deployment: 'cloud',
    apiStyle: 'openai-compatible',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    baseUrlEnv: 'OPENROUTER_BASE_URL',
    defaultBaseUrl: 'https://openrouter.ai/api/v1',
    modelEnv: 'OPENROUTER_MODEL',
    defaultModel: 'openai/gpt-4o-mini',
    capabilities: ['chat', 'reasoning', 'vision', 'tool-use'],
    scores: { quality: 8, speed: 7, cost: 8, privacy: 3 },
  },
  {
    id: 'groq',
    label: 'Groq',
    deployment: 'cloud',
    apiStyle: 'openai-compatible',
    apiKeyEnv: 'GROQ_API_KEY',
    baseUrlEnv: 'GROQ_BASE_URL',
    defaultBaseUrl: 'https://api.groq.com/openai/v1',
    modelEnv: 'GROQ_MODEL',
    defaultModel: 'llama-3.1-8b-instant',
    capabilities: ['chat', 'reasoning', 'tool-use'],
    scores: { quality: 7, speed: 10, cost: 7, privacy: 3 },
  },
  {
    id: 'ollama',
    label: 'Ollama / Local',
    deployment: 'local',
    apiStyle: 'openai-compatible',
    baseUrlEnv: 'OLLAMA_BASE_URL',
    defaultBaseUrl: 'http://127.0.0.1:11434/v1',
    modelEnv: 'OLLAMA_MODEL',
    defaultModel: 'llama3.1:8b',
    capabilities: ['chat', 'reasoning', 'embeddings', 'tool-use'],
    scores: { quality: 6, speed: 6, cost: 10, privacy: 10 },
  },
];
