const el = (id) => document.getElementById(id);

function inferArchetype(businessModel = '', description = '') {
  const text = `${businessModel} ${description}`.toLowerCase();
  if (text.includes('marketplace')) return 'Marketplace company';
  if (text.includes('ecommerce') || text.includes('e-commerce') || text.includes('shop')) return 'E-commerce company';
  if (text.includes('content') || text.includes('media')) return 'Content company';
  if (text.includes('lead') || text.includes('service')) return 'Revenue ops company';
  return 'Product operating company';
}

function buildRoles(archetype) {
  const common = [
    ['Operator', 'Runs priorities, execution rhythm, and the company pulse.'],
    ['CTO / Systems Lead', 'Owns architecture, infrastructure, model routing, and technical integrity.'],
    ['Product Lead', 'Owns roadmap, workflows, user value, and scope decisions.'],
    ['Growth Lead', 'Owns messaging, acquisition, activation, and conversion loops.'],
    ['QA / Reliability Lead', 'Owns trust, quality, monitoring, and resilience.'],
  ];

  if (archetype === 'Revenue ops company') {
    common.push(['Sales Ops Lead', 'Owns lead intake, qualification, and routing.']);
    common.push(['Follow-up Lead', 'Owns reminders, reactivation, and close support.']);
  } else if (archetype === 'Marketplace company') {
    common.push(['Supply Lead', 'Owns supply-side quality, onboarding, and health.']);
    common.push(['Demand Lead', 'Owns buyer funnel, matching, and demand health.']);
  } else {
    common.push(['Support Lead', 'Owns user issues, feedback loops, and support quality.']);
    common.push(['Research Lead', 'Owns strategic discovery and deeper market learning.']);
  }

  return common;
}

function selectRoutingProfile(description = '') {
  const text = description.toLowerCase();
  if (text.includes('premium') || text.includes('high-ticket')) {
    return {
      chat: 'Anthropic / OpenAI',
      reasoning: 'OpenAI / Anthropic',
      speed: 'Groq',
      privacy: 'Ollama / Local fallback',
    };
  }

  return {
    chat: 'OpenAI / OpenRouter',
    reasoning: 'Anthropic / OpenAI',
    speed: 'Groq',
    privacy: 'Ollama / Local fallback',
  };
}

function buildMissions(projectName, goals) {
  return [
    `Turn ${projectName} into a fully operational AI company, not just a product shell.`,
    `Win the first week around: ${goals}.`,
    'Stand up one reliable daily execution loop with visible outcomes.',
    'Keep communication compact, ownership clear, and blockers explicit.',
  ];
}

function renderBrand(data, archetype) {
  const rows = [
    ['Project', data.projectName],
    ['Positioning', `${archetype} generated by MultiClaw`],
    ['Audience', data.audience],
    ['Business model', data.businessModel],
    ['Tone', data.tone],
  ];

  return rows.map(([label, value]) => `
    <div class="brand-row">
      <small>${label}</small>
      <strong>${value}</strong>
      <p>${label === 'Positioning' ? 'A coordinated AI company designed to run this project with structure, speed, and clear ownership.' : 'Generated from the founder intake and used as operating context.'}</p>
    </div>
  `).join('');
}

function renderRouting(profile) {
  return Object.entries(profile).map(([label, value]) => `
    <div class="route-card">
      <small>${label}</small>
      <strong>${value}</strong>
      <p>Selected as the current default routing posture for this capability.</p>
    </div>
  `).join('');
}

function renderOrg(roles) {
  return roles.map(([title, scope]) => `
    <div class="role-card">
      <h4>${title}</h4>
      <p>${scope}</p>
    </div>
  `).join('');
}

function renderMissions(projectName, goals) {
  return buildMissions(projectName, goals).map((item, index) => `
    <div class="mission-card">
      <small>Mission ${index + 1}</small>
      <strong>${item}</strong>
      <p>Immediate operating focus for the first company cycle.</p>
    </div>
  `).join('');
}

function getFormData() {
  return {
    projectName: el('projectName').value.trim() || 'Untitled Project',
    description: el('description').value.trim(),
    audience: el('audience').value.trim(),
    businessModel: el('businessModel').value.trim(),
    stage: el('stage').value,
    topGoals: el('topGoals').value.trim(),
    tone: el('tone').value.trim(),
  };
}

function render() {
  const data = getFormData();
  const archetype = inferArchetype(data.businessModel, data.description);
  const roles = buildRoles(archetype);
  const routing = selectRoutingProfile(data.description);

  el('heroTitle').textContent = `${data.projectName}, powered by MultiClaw`;
  el('heroSubtitle').textContent = `${data.description} This company is designed as a ${archetype.toLowerCase()} with ${data.stage.toLowerCase()} urgency.`;
  el('departmentsCount').textContent = '5';
  el('rolesCount').textContent = String(roles.length);
  el('brandCard').innerHTML = renderBrand(data, archetype);
  el('routingCard').innerHTML = renderRouting(routing);
  el('orgGrid').innerHTML = renderOrg(roles);
  el('missionBoard').innerHTML = renderMissions(data.projectName, data.topGoals);
}

el('generateBtn').addEventListener('click', render);
render();
