import { mountSession, requireAuth } from './auth.js';

await requireAuth();
mountSession();

const el = (id) => document.getElementById(id);

const PRESETS = {
  saas: {
    productOrigin: 'Existing product',
    autonomyMode: 'Operator-assisted',
    projectName: 'FlowPilot',
    description: 'A premium AI workflow platform for software teams.',
    existingAssets: '',
    audience: 'Software teams',
    businessModel: 'SaaS',
    stage: 'Growth',
    topGoals: 'Ship faster, onboard users, retain customers',
    tone: 'Sharp, premium, operational',
    roleTemplate: 'Balanced',
    customRoles: '',
  },
  revenue: {
    productOrigin: 'Homegrown app',
    autonomyMode: 'Full autonomous',
    projectName: 'CloseForge',
    description: 'An AI revenue operations layer for high-ticket service businesses.',
    existingAssets: 'CRM\nFollow-up system',
    audience: 'High-ticket service businesses',
    businessModel: 'SaaS with optional services',
    stage: 'Growth',
    topGoals: 'Close customers, recover leads, run like a company',
    tone: 'Sharp, confident, premium',
    roleTemplate: 'Go-to-market',
    customRoles: 'CFO / Finance Lead | Owns budget awareness and business health',
  },
  marketplace: {
    productOrigin: 'Existing product',
    autonomyMode: 'Operator-assisted',
    projectName: 'MatchGrid',
    description: 'A premium marketplace that coordinates supply, demand, and operations with AI.',
    existingAssets: '',
    audience: 'Marketplace operators',
    businessModel: 'Marketplace',
    stage: 'MVP',
    topGoals: 'Validate matching, grow liquidity, tighten operations',
    tone: 'Structured, premium, decisive',
    roleTemplate: 'Executive',
    customRoles: '',
  },
};

const SETTINGS_KEY = 'multiclaw-settings';
const params = new URLSearchParams(window.location.search);
const companyIdToRefine = params.get('companyId');
let currentStep = 1;
const totalSteps = 3;

function loadSettings() {
  try {
    return JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{}');
  } catch {
    return {};
  }
}

function escapeHtml(value) {
  return String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#39;');
}

function renderBrand(data) {
  const rows = [
    ['Project', data.projectName],
    ['Company ID', data.companyId],
    ['Product origin', data.productOrigin],
    ['Autonomy mode', data.autonomyMode],
    ['Positioning', `${data.archetype} generated by MultiClaw`],
    ['Audience', data.audience],
    ['Business model', data.businessModel],
    ['Tone', data.tone],
  ];

  return rows.map(([label, value]) => `
    <div class="brand-row">
      <small>${escapeHtml(label)}</small>
      <strong>${escapeHtml(value)}</strong>
      <p>${label === 'Company ID' ? 'Safe public identifier for the generated company, without exposing server internals.' : 'Generated from the company brief and used as operating context.'}</p>
    </div>
  `).join('');
}

function renderRouting(profile) {
  return Object.entries(profile).map(([label, value]) => `
    <div class="route-card">
      <small>${escapeHtml(label)}</small>
      <strong>${escapeHtml(value)}</strong>
      <p>Selected as the current default routing posture for this capability.</p>
    </div>
  `).join('');
}

function renderOrg(roles) {
  return roles.map((role) => `
    <div class="role-card">
      <h4>${escapeHtml(role.title)}</h4>
      <p>${escapeHtml(role.scope)}</p>
    </div>
  `).join('');
}

function renderMissions(missions) {
  return missions.map((item, index) => `
    <div class="mission-card">
      <small>Mission ${index + 1}</small>
      <strong>${escapeHtml(item)}</strong>
      <p>Immediate operating focus for the first company cycle.</p>
    </div>
  `).join('');
}

function estimateArchetype(data) {
  const text = `${data.businessModel || ''} ${data.description || ''}`.toLowerCase();
  if (text.includes('marketplace')) return 'marketplace company';
  if (text.includes('content') || text.includes('media')) return 'content company';
  if (text.includes('service') || text.includes('lead')) return 'revenue ops company';
  return 'product operating company';
}

function countCustomRoles(rawValue) {
  return (rawValue || '').split('\n').map((line) => line.trim()).filter(Boolean).length;
}

function estimateRolesCount(data) {
  const templateCount = {
    Balanced: 0,
    Executive: 2,
    'Engineering-heavy': 2,
    'Go-to-market': 2,
  }[data.roleTemplate] || 0;
  return 7 + templateCount + countCustomRoles(data.customRoles);
}

function updateLivePreview() {
  const data = getFormData();
  el('heroTitle').textContent = `${data.projectName || 'Untitled Project'}, powered by MultiClaw`;
  el('heroSubtitle').textContent = `${data.description || 'A living AI company generated around your target system.'} This company is shaping into a ${estimateArchetype(data)}.`;
  el('rolesCount').textContent = String(estimateRolesCount(data));
  el('departmentsCount').textContent = String(Math.max(5, Math.min(12, estimateRolesCount(data))));
}

function getFormData() {
  return {
    productOrigin: el('productOrigin').value,
    autonomyMode: el('autonomyMode').value,
    projectName: el('projectName').value.trim() || 'Untitled Project',
    description: el('description').value.trim(),
    existingAssets: el('existingAssets').value.trim(),
    audience: el('audience').value.trim(),
    businessModel: el('businessModel').value.trim(),
    stage: el('stage').value,
    topGoals: el('topGoals').value.trim(),
    tone: el('tone').value.trim(),
    roleTemplate: el('roleTemplate').value,
    customRoles: el('customRoles').value.trim(),
  };
}

function setStatus(message, kind = 'idle') {
  const status = el('generationStatus');
  status.textContent = message;
  status.className = `status-banner status-${kind}`;
}

function setCompanyLink(companyId) {
  const link = el('companyLink');
  const download = el('downloadPackLink');
  link.href = `./company.html?id=${encodeURIComponent(companyId)}`;
  link.classList.remove('hidden-link');
  download.href = `/api/company/${encodeURIComponent(companyId)}/download`;
  download.classList.remove('hidden-link');
}

function applyResult(data) {
  el('heroTitle').textContent = `${data.projectName}, powered by MultiClaw`;
  el('heroSubtitle').textContent = `${data.description} This company is designed as a ${data.archetype.toLowerCase()} with ${data.stage.toLowerCase()} urgency.`;
  el('departmentsCount').textContent = String(data.departmentsCount);
  el('rolesCount').textContent = String(data.rolesCount);
  el('brandCard').innerHTML = renderBrand(data);
  el('routingCard').innerHTML = renderRouting(data.routing);
  el('orgGrid').innerHTML = renderOrg(data.roles);
  el('missionBoard').innerHTML = renderMissions(data.missions);
  const stamp = new Date().toLocaleTimeString();
  setStatus(`Company generated successfully at ${stamp}. ID: ${data.companyId}`, 'success');
  setCompanyLink(data.companyId);
}

function applyPreset(name) {
  const preset = PRESETS[name];
  if (!preset) return;

  el('productOrigin').value = preset.productOrigin;
  el('autonomyMode').value = preset.autonomyMode;
  el('projectName').value = preset.projectName;
  el('description').value = preset.description;
  if (typeof preset.existingAssets === 'string') el('existingAssets').value = preset.existingAssets;
  el('audience').value = preset.audience;
  el('businessModel').value = preset.businessModel;
  el('stage').value = preset.stage;
  el('topGoals').value = preset.topGoals;
  el('tone').value = preset.tone;
  if (preset.roleTemplate) el('roleTemplate').value = preset.roleTemplate;
  if (typeof preset.customRoles === 'string') el('customRoles').value = preset.customRoles;
  setStatus(`Preset loaded: ${preset.projectName}`, 'idle');
}

function fillForm(data) {
  if (data.productOrigin) el('productOrigin').value = data.productOrigin;
  if (data.autonomyMode) el('autonomyMode').value = data.autonomyMode;
  if (data.projectName) el('projectName').value = data.projectName;
  if (data.description) el('description').value = data.description;
  if (Array.isArray(data.existingAssets)) el('existingAssets').value = data.existingAssets.join('\n');
  if (data.audience) el('audience').value = data.audience;
  if (data.businessModel) el('businessModel').value = data.businessModel;
  if (data.stage) el('stage').value = data.stage;
  if (data.topGoals) el('topGoals').value = data.topGoals;
  if (data.tone) el('tone').value = data.tone;
  if (data.roleTemplate) el('roleTemplate').value = data.roleTemplate;
  if (typeof data.customRoles === 'string') el('customRoles').value = data.customRoles;
}

async function loadCompanyForRefinement() {
  if (!companyIdToRefine) return;
  try {
    const response = await fetch(`/api/company/${encodeURIComponent(companyIdToRefine)}`);
    if (!response.ok) throw new Error(`Failed with status ${response.status}`);
    const company = await response.json();
    fillForm(company);
    setStatus(`Loaded ${company.projectName} for refinement.`, 'idle');
  } catch (error) {
    console.error(error);
    setStatus('Could not load company for refinement.', 'error');
  }
}

function renderWizard() {
  document.querySelectorAll('.wizard-step').forEach((step) => {
    step.classList.toggle('active', Number(step.dataset.step) === currentStep);
  });

  document.querySelectorAll('.wizard-dot').forEach((dot, index) => {
    dot.classList.toggle('active', index + 1 <= currentStep);
  });

  el('stepLabel').textContent = `Step ${currentStep} of ${totalSteps}`;
  el('backBtn').style.visibility = currentStep === 1 ? 'hidden' : 'visible';
  el('nextBtn').classList.toggle('hidden-link', currentStep === totalSteps);
  el('generateBtn').classList.toggle('hidden-link', currentStep !== totalSteps);
}

async function generateCompany() {
  const button = el('generateBtn');
  const original = button.textContent;
  button.textContent = 'Generating...';
  button.disabled = true;
  setStatus('Generating company...', 'working');

  try {
    const response = await fetch('/api/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(getFormData()),
      credentials: 'same-origin',
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error.error || `Generation failed with status ${response.status}`);
    }

    const data = await response.json();
    applyResult(data);
  } catch (error) {
    console.error(error);
    setStatus(error.message || 'Generation failed. Check the server log.', 'error');
    alert(error.message || 'Generation failed. Check the server log.');
  } finally {
    button.textContent = original;
    button.disabled = false;
  }
}

el('nextBtn').addEventListener('click', () => {
  if (currentStep < totalSteps) {
    currentStep += 1;
    renderWizard();
  }
});

el('backBtn').addEventListener('click', () => {
  if (currentStep > 1) {
    currentStep -= 1;
    renderWizard();
  }
});

el('generateBtn').addEventListener('click', generateCompany);
document.querySelectorAll('[data-preset]').forEach((button) => {
  button.addEventListener('click', () => applyPreset(button.dataset.preset));
});

const savedSettings = loadSettings();
if (savedSettings.defaultProductOrigin) el('productOrigin').value = savedSettings.defaultProductOrigin;
if (savedSettings.defaultAutonomyMode) el('autonomyMode').value = savedSettings.defaultAutonomyMode;

renderWizard();
await loadCompanyForRefinement();
updateLivePreview();

document.querySelectorAll('input, textarea, select').forEach((field) => {
  field.addEventListener('input', updateLivePreview);
  field.addEventListener('change', updateLivePreview);
});
